### ISSUE TITLE
TypeScript fails when using latest `@ember/test-helpers`

### ISSUE THREAD

**Issue by simonihmig** [ember-a11y/ember-a11y-testing#498]
The latest version of `@ember/test-helpers` ships its own types, so `@types/ember__test-helpers` is obsolete now (see https://github.com/typed-ember/ember-cli-typescript/pull/1545).

In a project with that setup (i.e. no `@types/ember__test-helpers`) I am getting this when installing ember-a11y-testing:

```
../node_modules/.pnpm/ember-a11y-testing@5.2.0_xxksirw4yhzqkev2rkehjstyum/node_modules/ember-a11y-testing/test-support/setup-middleware-reporter.d.ts:1:23 - error TS2688: Cannot find type definition file for 'ember__test-helpers'
[tests] 1 /// <reference types="ember__test-helpers" />
```

See the `<reference types="ember__test-helpers" />` in the compiled `setup-middleware-reporter.d.ts`, which now references a non-existing file.

**Comment by NullVoxPopuli** [comment]
I think @gitKrystan knows the solution to this type of problem?

**Comment by simonihmig** [comment]
Maybe updating `@ember/test-helpers` and dropping `@types/ember__test-helpers` _here_ would help?

**Comment by drewlee** [comment]
The `registerHook` and `runHooks` functions need to be exposed as official public APIs in `@ember/test-helpers`. This should be fine since they've been in use for several years now. Ember-a11y-testing currently [defines these types locally](https://github.com/ember-a11y/ember-a11y-testing/blob/master/types/%40ember/test-helpers.d.ts.), which unfortunately impedes upgrading `@ember/test-helpers`.

**Comment by gitKrystan** [comment]
This looks to be the same issue I found in ember-modifier (and we'll probably find in more repos as `@types` packages start getting dropped).

> While this project doesn't add the reference directive directly, it appears that with `types: []` ([the default for @tsconfig/ember](https://github.com/tsconfig/bases/pull/149)), the compiler will helpfully(?) add the directive for you. (See https://github.com/microsoft/TypeScript/issues/19874)

There are two possible solutions:

1. Quick but not ideal: https://github.com/ember-modifier/ember-modifier/pull/657
2. Ideal but not quick: https://github.com/ember-modifier/ember-modifier/pull/665 (NOTE: This one isn't ready to merge, so see the discussion in the comments for the Right Way™️.)

**Comment by gitKrystan** [comment]
Re: `registerHook` and `runHooks`, it appears that `@ember/test-helpers` exposes them as `_registerHook` and `_runHooks`. Will this unblock you?

https://github.com/emberjs/ember-test-helpers/blob/fbfc9c5bbfee500c1be456f6bc1eec15ebe07872/addon-test-support/%40ember/test-helpers/index.ts#L52-L55

**Comment by drewlee** [comment]
@gitKrystan Yeah, this is how ember-a11y-testing is currently leveraging these APIs. Unfortunately, they're still considered private methods in `@ember/test-helpers`, so no typings are currently being provided for them.

**Comment by gitKrystan** [comment]
My understanding is that the types shipped directly from `@ember/test-helpers` should include them as long as they are exported in that file.

**Comment by drewlee** [comment]
For type inference, yes. However, the types need to be exported explicitly for cases where they need to be used in direct variable/argument assignments.

**Comment by gitKrystan** [comment]
Are you saying you need these types exported?

https://github.com/emberjs/ember-test-helpers/blob/fbfc9c5bbfee500c1be456f6bc1eec15ebe07872/addon-test-support/%40ember/test-helpers/-internal/helper-hooks.ts#L1-L5

If so, I can help with that. I've been working on unblocking people from using the `@ember/test-helpers` types directly (thus unblocking Ember preview types for a lot of people).

**Comment by drewlee** [comment]
Correct. I'm actually in the process of handling this via https://github.com/emberjs/ember-test-helpers/issues/1341.

**Comment by gitKrystan** [comment]
Whoops I didn't see that so duplicated your work. I'll close mine. 😅

**Comment by drewlee** [comment]
PR for `@ember/test-helpers`: https://github.com/emberjs/ember-test-helpers/pull/1344

**Comment by acorncom** [comment]
@simonihmig is this resolved by the latest `@ember/test-helpers` ?

**Comment by MelSumner** [comment]
We have releases out that should satisfy these concerns, so I'm going to close this issue. Please re-open this issue if you find that the new releases do not resolve your issue.

**Comment by NullVoxPopuli** [comment]
@gitKrystan  idk if avoiding `types: []` is the solution? 

I made an attempt here: https://github.com/tildeio/ember-element-helper/pull/112 but no dice -- `/// reference` is still present in the `declarations` outptu
